# Generated by Django 4.2.1 on 2023-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to='profil_img'),
        ),
    ]
