# Generated by Django 4.2.1 on 2023-05-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
